package com.model;
// Generated 05 20, 15 2:11:56 PM by Hibernate Tools 4.3.1



/**
 * CoursesAssigned generated by hbm2java
 */
public class CoursesAssigned  implements java.io.Serializable {


     private int assignmentId;
     private Course course;
     private UserDetails userDetails;

    public CoursesAssigned() {
    }

    public CoursesAssigned(int assignmentId, Course course, UserDetails userDetails) {
       this.assignmentId = assignmentId;
       this.course = course;
       this.userDetails = userDetails;
    }
   
    public int getAssignmentId() {
        return this.assignmentId;
    }
    
    public void setAssignmentId(int assignmentId) {
        this.assignmentId = assignmentId;
    }
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }
    public UserDetails getUserDetails() {
        return this.userDetails;
    }
    
    public void setUserDetails(UserDetails userDetails) {
        this.userDetails = userDetails;
    }




}


