package com.model;
// Generated 05 19, 15 11:49:40 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CourseCategory generated by hbm2java
 */
public class CourseCategory  implements java.io.Serializable {


     private int courseCategoryId;
     private String courseCategory;
     private Set<Course> courses = new HashSet<Course>(0);

    public CourseCategory() {
    }

	
    public CourseCategory(int courseCategoryId, String courseCategory) {
        this.courseCategoryId = courseCategoryId;
        this.courseCategory = courseCategory;
    }
    public CourseCategory(int courseCategoryId, String courseCategory, Set<Course> courses) {
       this.courseCategoryId = courseCategoryId;
       this.courseCategory = courseCategory;
       this.courses = courses;
    }
   
    public int getCourseCategoryId() {
        return this.courseCategoryId;
    }
    
    public void setCourseCategoryId(int courseCategoryId) {
        this.courseCategoryId = courseCategoryId;
    }
    public String getCourseCategory() {
        return this.courseCategory;
    }
    
    public void setCourseCategory(String courseCategory) {
        this.courseCategory = courseCategory;
    }
    public Set<Course> getCourses() {
        return this.courses;
    }
    
    public void setCourses(Set<Course> courses) {
        this.courses = courses;
    }




}


