package com.model;
// Generated 05 19, 15 11:49:40 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ExamScores generated by hbm2java
 */
public class ExamScores  implements java.io.Serializable {


     private int examId;
     private Exam exam;
     private UserDetails userDetails;
     private Date dateTaken;
     private int score;
     private int maxScore;

    public ExamScores() {
    }

    public ExamScores(int examId, Exam exam, UserDetails userDetails, Date dateTaken, int score, int maxScore) {
       this.examId = examId;
       this.exam = exam;
       this.userDetails = userDetails;
       this.dateTaken = dateTaken;
       this.score = score;
       this.maxScore = maxScore;
    }
   
    public int getExamId() {
        return this.examId;
    }
    
    public void setExamId(int examId) {
        this.examId = examId;
    }
    public Exam getExam() {
        return this.exam;
    }
    
    public void setExam(Exam exam) {
        this.exam = exam;
    }
    public UserDetails getUserDetails() {
        return this.userDetails;
    }
    
    public void setUserDetails(UserDetails userDetails) {
        this.userDetails = userDetails;
    }
    public Date getDateTaken() {
        return this.dateTaken;
    }
    
    public void setDateTaken(Date dateTaken) {
        this.dateTaken = dateTaken;
    }
    public int getScore() {
        return this.score;
    }
    
    public void setScore(int score) {
        this.score = score;
    }
    public int getMaxScore() {
        return this.maxScore;
    }
    
    public void setMaxScore(int maxScore) {
        this.maxScore = maxScore;
    }




}


