package com.model;
// Generated 05 19, 15 11:49:40 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Presentation generated by hbm2java
 */
public class Presentation  implements java.io.Serializable {


     private int presentationId;
     private Chapter chapter;
     private String fileName;
     private String fileType;
     private double fileSize;
     private String filePath;
     private String description;
     private Date dateUploaded;
     private boolean recordStatus;

    public Presentation() {
    }

    public Presentation(int presentationId, Chapter chapter, String fileName, String fileType, double fileSize, String filePath, String description, Date dateUploaded, boolean recordStatus) {
       this.presentationId = presentationId;
       this.chapter = chapter;
       this.fileName = fileName;
       this.fileType = fileType;
       this.fileSize = fileSize;
       this.filePath = filePath;
       this.description = description;
       this.dateUploaded = dateUploaded;
       this.recordStatus = recordStatus;
    }
   
    public int getPresentationId() {
        return this.presentationId;
    }
    
    public void setPresentationId(int presentationId) {
        this.presentationId = presentationId;
    }
    public Chapter getChapter() {
        return this.chapter;
    }
    
    public void setChapter(Chapter chapter) {
        this.chapter = chapter;
    }
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    public String getFileType() {
        return this.fileType;
    }
    
    public void setFileType(String fileType) {
        this.fileType = fileType;
    }
    public double getFileSize() {
        return this.fileSize;
    }
    
    public void setFileSize(double fileSize) {
        this.fileSize = fileSize;
    }
    public String getFilePath() {
        return this.filePath;
    }
    
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getDateUploaded() {
        return this.dateUploaded;
    }
    
    public void setDateUploaded(Date dateUploaded) {
        this.dateUploaded = dateUploaded;
    }
    public boolean isRecordStatus() {
        return this.recordStatus;
    }
    
    public void setRecordStatus(boolean recordStatus) {
        this.recordStatus = recordStatus;
    }




}


